[package]
name = "catcoms-discovery"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
catcoms-rt = { path = "../catcoms-rt" }
catcoms-wire = { path = "../catcoms-wire" }
tracing.workspace = true
blake3 = "1"
multiaddr = "0.18"
thiserror.workspace = true

[dev-dependencies]
rand_chacha = "0.3"
rand_core = "0.6"

[lints]
workspace = true
