//! Opt-in registry receive adapter. Network ticks only authenticate/queue bounded packets;
//! explicit drains run the existing accounted durable store admission under exclusive access.

use crate::store::{epoch_budget::EpochStorageBudget, EpochRegistryState};
use crate::{AppError, Server, ServerStore};
use catcoms_replication::{epoch_zero_id, registry::registry_document, Admission};
use catcoms_rt::{CryptoRngCore, MeshTransport};
use catcoms_sync::RegistryWatch;
use catcoms_wire::DocType;
use std::sync::Arc;

/// Non-cloneable watch bound to an exact sync instance, vault mount, local server and bucket.
/// Its sync token additionally pins concrete epoch and installation generation. Never a UI lease.
pub struct ServerRegistryWatch {
    pub(crate) inner: RegistryWatch,
    pub(crate) mount: Arc<()>,
    pub(crate) server: u64,
    pub(crate) bucket: u8,
}
impl std::fmt::Debug for ServerRegistryWatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ServerRegistryWatch { .. }")
    }
}

/// Returned only after durable admission succeeds. Quarantine/duplicate are not newly accepted
/// edits or delivery/finality evidence; no network delivery receipt is generated by this slice.
#[derive(Debug)]
pub struct RegistryReceived {
    pub admission: Admission,
    pub state: EpochRegistryState,
}

impl<T: MeshTransport, R: CryptoRngCore> Server<T, R> {
    /// Capture the checked local concrete epoch, or deterministic epoch zero ONLY when absent.
    /// Installation is synchronous so the caller owns its revocation handle before any await.
    /// No epoch file is created and no bucket is discovered by this operation. Subscription is
    /// reconciled by the next sync_once or explicit flush_registry_subscriptions call.
    pub fn watch_registry_epoch(
        &mut self,
        store: &ServerStore,
        server: u64,
        bucket: u8,
    ) -> Result<ServerRegistryWatch, AppError> {
        let id = self.sync.with_registry_context(|group, device, _, _| {
            if group.member_signature_key(&device.device_id()).as_deref()
                != Some(device.public_key_bytes().as_slice())
            {
                return Err(AppError::Invalid(
                    "registry receiver is not a current member".into(),
                ));
            }
            let state = store.load_registry_epoch(server, group, bucket, device)?;
            let document = registry_document(&group.group_id(), bucket)
                .map_err(|error| AppError::Invalid(error.to_string()))?;
            Ok(state
                .map(|state| state.doc_id())
                .unwrap_or_else(|| epoch_zero_id(DocType::DocRegistry, &document.logical_key)))
        })?;
        Ok(ServerRegistryWatch {
            inner: self.sync.watch_registry(bucket, id),
            mount: store.registry_mount(),
            server,
            bucket,
        })
    }

    pub(crate) fn check_registry_watch(
        &self,
        store: &ServerStore,
        watch: &ServerRegistryWatch,
    ) -> Result<(), AppError> {
        if !Arc::ptr_eq(&watch.mount, &store.registry_mount())
            || !self.sync.registry_watch_is_current(&watch.inner)
        {
            return Err(AppError::Invalid(
                "registry watch belongs to a replaced mount, server or epoch".into(),
            ));
        }
        Ok(())
    }

    /// Flush desired routing subscriptions without waiting for an incoming event. Cancellation
    /// preserves the installed watch and the sync layer's bounded reconciliation ownership.
    pub async fn flush_registry_subscriptions(&mut self) -> Result<(), AppError> {
        Ok(self.sync.flush_registry_subscriptions().await?)
    }

    /// Revoke this exact watch immediately. Dropping a handle alone does not unsubscribe; callers
    /// must explicitly unwatch on close or replace it when the persisted concrete epoch changes.
    /// Revocation performs no store I/O and deliberately needs no live mount: after reopening the
    /// vault an old handle must still be able to discard its own queued traffic. Exact sync/watch
    /// generation checks prevent that handle from revoking a replacement.
    pub fn unwatch_registry_epoch(&mut self, watch: &ServerRegistryWatch) -> Result<(), AppError> {
        Ok(self.sync.unwatch_registry(&watch.inner)?)
    }

    /// Apply at most one packet through the existing gate, full-author checks and vault barrier.
    /// No caller-supplied packet/server id can retarget the watch. A failure consumes volatile
    /// traffic without acknowledgement; the sender's durable intent/future catch-up must recover it.
    /// Complete trusted inventory remains mandatory, and an epoch rotation requires a fresh watch.
    pub fn receive_registry_step(
        &mut self,
        store: &mut ServerStore,
        watch: &ServerRegistryWatch,
        budget: &mut EpochStorageBudget,
    ) -> Result<Option<RegistryReceived>, AppError> {
        self.check_registry_watch(store, watch)?;
        self.sync
            .drain_registry_inbound(&watch.inner, |group, device, rng, sealed| {
                store
                    .ingest_registry_epoch(
                        watch.server,
                        group,
                        watch.bucket,
                        device,
                        sealed,
                        rng,
                        budget,
                    )
                    .map(|(admission, state)| RegistryReceived { admission, state })
            })?
            .transpose()
    }
}

#[cfg(test)]
mod tests;
